### ISSUE TITLE
Improve the app - at least 5 things based on peer review + TA feedback

### ISSUE THREAD

**Issue by GloriaWYY** [UBC-MDS/safe_vancity#45]

**Comment by arlincherian** [comment]
Here are ways we have implemented changes in our app based on peer review + TA comments from Milestone 1:

1. Comment: To make the map more interlinked with the other plots, it might be good to explore area selection in the map which will modify the remaining plots accordingly.

- This is how the map is implemented, you select a neighbourhood, and all the maps/plots change based on this. For example, you select “Kitsilano” on the filter and the map shows crime density in Kitsilano, the two bar plots show their respective stats in Kitsilano. Unclear about what is meant by “area selection”.
2. Comment: Currently, the plots are neighbourhood specific. For future improvement, it might be nice for the app to have plots for 'All' neighbourhoods.
- Functionality of this was harder to implement, instead, we provided high-level statistics of crime incidents in all of Vancouver, total property crimes, total violent crimes, total vehicle collision crimes etc so this information is available to the users before they dive into neighbourhood specific stats. 
- Commit link: https://github.com/UBC-MDS/safe_vancity/commit/31b30c24dff6b0d1cc0fd1cdb630d82f22932509 

3. Comment: The default view of the map after each selection of the crime type is quite zoomed out. A closer look into the area could be nice to review the spread of cases for the type of crime selected.
- The poorly map has the function to zoom in and out. We believe this functionality works and is sufficient as the user can zoom into specific streets/neighbourhoods etc. The scatter map is also centred around a specific latitude/long, therefore, increasing the zoom size too much means the map plot maybe zoomed into a specific location and the user will have to zoom out to see the density in specific neighbourhoods. 
- Commit Link: https://github.com/UBC-MDS/safe_vancity/commit/31b30c24dff6b0d1cc0fd1cdb630d82f22932509 
4. Comment: For someone with no technical knowledge of dashboards, it would be nice to include some information on how to operate the plots (something like a help button). The plots in the app are more or less self-explanatory. Although, it would be good to have a small section that documents the key takeaways from the app and how to use it efficiently.
- An about section was added with info to the project GitHub repo,  detailed description about the plots, how to use them and what to derive from them. 
- Commit Link: https://github.com/UBC-MDS/safe_vancity/commit/aefae7963cb6bb7b54810a4259bba6aa8e8953325.                                                                          
5. Just a suggestion - it would be nice if the horizontal bar chart would highlight the crime type selected in the filter on the left.
- We thought this was a good idea and have implemented this in our dashboard
- Commit Link: https://github.com/UBC-MDS/safe_vancity/commit/3c9ef62b83a399e70235357aec30f228ef0cbe80 

Additional TA comment:

1. Comment from TA about describing acronyms before using them.
- Adjusted the proposal document to explain the variables used, new variables that were created for analysis and visualizations. 
- Commit Link: https://github.com/UBC-MDS/safe_vancity/commit/dabd5dde335b3ce4ab067a2479d6c2af0b84f29e
